name: ci

env:
  CTEST_PARALLEL_LEVEL: 3
  CMAKE_BUILD_TYPE: Release
  CMAKE_GENERATOR: Ninja
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**/*.f"
      - "**/*.f90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci.yml"

jobs:

  linux_mac:
    strategy:
      matrix:
        shared: [true, false]
        msis2: [true, false]
        image: [
          {os: ubuntu-latest, fc: gfortran, cmd: sudo apt update && sudo apt install libhdf5-dev},
          {os: macos-latest, fc: gfortran-11, cmd: brew install hdf5}
        ]

    runs-on: ${{ matrix.image.os }}
    timeout-minutes: 15
    env:
      FC: ${{ matrix.image.fc }}

    steps:
    - uses: actions/checkout@v2

    - name: Install system libs
      run: ${{ matrix.image.cmd }}

    - name: Get specific version CMake
      uses: lukka/get-cmake@v3.20.1

    - name: Download h5fortran
      uses: actions/checkout@v2
      with:
        repository: geospace-code/h5fortran
        path: h5fortran

    - name: Install h5fortran
      timeout-minutes: 10
      run: |
        cmake -S $GITHUB_WORKSPACE/h5fortran -B $GITHUB_WORKSPACE/h5fortran/build -DCMAKE_INSTALL_PREFIX=${HOME} -DBUILD_TESTING=no -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
        cmake --build $GITHUB_WORKSPACE/h5fortran/build
        cmake --install $GITHUB_WORKSPACE/h5fortran/build

    - name: Configure MSIS
      run: cmake -B build -Dmsis2:BOOL=${{ matrix.msis2 }} -DCMAKE_PREFIX_PATH=${HOME} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}

    - name: Build MSIS
      run: cmake --build build

    - name: Test MSIS
      run: ctest --test-dir build --no-tests=error -V
