name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.f"
      - "**.f90"
      - "**.F90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci.yml"

jobs:

  core:
    strategy:
      matrix:
        shared: [true, false]
        msis2: [true, false]
        image: [
          {os: ubuntu-latest, cmd: sudo apt update && sudo apt install libhdf5-mpi-dev},
          {os: macos-latest, cmd: brew install hdf5-mpi && brew reinstall gcc}
        ]

    runs-on: ${{ matrix.image.os }}
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3

    - name: Install system libs
      run: ${{ matrix.image.cmd }}

    - name: Download h5fortran
      uses: actions/checkout@v3
      with:
        repository: geospace-code/h5fortran-mpi
        path: h5fortran

    - name: Install h5fortran
      timeout-minutes: 10
      run: |
        cmake -S h5fortran -B h5fortran/build -DCMAKE_INSTALL_PREFIX=${{ runner.temp }} -DBUILD_TESTING=no -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
        cmake --build h5fortran/build --parallel
        cmake --install h5fortran/build

    - name: Configure MSIS msis2=${{ matrix.msis2 }} shared=${{ matrix.shared }}
      run: >-
        cmake -B build
        -Dmsis2:BOOL=${{ matrix.msis2 }}
        -DCMAKE_PREFIX_PATH=${{ runner.temp }}
        -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
        -DCMAKE_INSTALL_PREFIX=${{ runner.temp }}

    - name: Build MSIS
      run: cmake --build build --parallel || cmake --build build -v

    - name: Test MSIS
      run: ctest --test-dir build --preset default -V

    - name: Install MSIS
      run: cmake --install build

    - name: configure Example
      run: cmake -S example -B example/build -DCMAKE_PREFIX_PATH=${{ runner.temp }}

    - name: Build Example
      run: cmake --build example/build --parallel

    - name: Test Example
      run: ctest --test-dir example/build -V


  # windows:
  #   timeout-minutes: 20
  #   runs-on: windows-latest
  #   env:
  #     CMAKE_GENERATOR: MinGW Makefiles

  #   strategy:
  #     matrix:
  #       msis2: [true, false]
  #       # shared: [true, false]
  #       # shared always error 135 even on only msis shared. not a problem on real pc.

  #   steps:
  #   - uses: msys2/setup-msys2@v2
  #     with:
  #       update: true
  #       install: >-
  #         mingw-w64-x86_64-gcc-fortran
  #         mingw-w64-x86_64-hdf5

  #   - name: Put MSYS2_MinGW64 on PATH
  #     # this is because GNU Patch doesn't work from MSYS2 shell
  #     run: echo "${{ runner.temp }}/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

  #   - uses: actions/checkout@v3

  #   - name: Download h5fortran
  #     uses: actions/checkout@v3
  #     with:
  #       repository: geospace-code/h5fortran
  #       path: h5fortran

  #   - name: Install h5fortran
  #     timeout-minutes: 10
  #     run: |
  #       cmake -S h5fortran -B h5fortran/build -DCMAKE_INSTALL_PREFIX=${{ runner.temp }} -DBUILD_TESTING=no
  #       cmake --build h5fortran/build
  #       cmake --install h5fortran/build

  #   - name: Configure MSIS
  #     run: cmake -B build -Dmsis2:BOOL=${{ matrix.msis2 }} -DCMAKE_PREFIX_PATH=${{ runner.temp }}

  #   - name: Build MSIS
  #     run: cmake --build build

  #   - name: Test MSIS
  #     run: ctest --test-dir build  --preset default -V
